<option value="Ash Sharqia">Ash Sharqia</option>
<option value="Giza">Giza</option>
<option value="North Sinai">North Sinai</option>
<option value="Gharbia">Gharbia</option>
<option value="Dakahlia">Dakahlia</option>
<option value="Alexandria">Alexandria</option>
<option value="Asyut">Asyut</option>
<option value="Aswan">Aswan</option>
<option value="Beni Suef">Beni Suef</option>
<option value="Qalyubia">Qalyubia</option>
<option value="Cairo">Cairo</option>
<option value="Beheira">Beheira</option>
<option value="Damietta">Damietta</option>
<option value="New Valley">New Valley</option>
<option value="Faiyum">Faiyum</option>
<option value="Red Sea">Red Sea</option>
<option value="Ismailia">Ismailia</option>
<option value="Kafr El Sheikh">Kafr El Sheikh</option>
<option value="Luxor">Luxor</option>
<option value="Matrouh">Matrouh</option>
<option value="Minya">Minya</option>
<option value="Port Said">Port Said</option>
<option value="Qena">Qena</option>
<option value="Menofia">Menofia</option>
<option value="South Sinai">South Sinai</option>
<option value="Sohag">Sohag</option>
<option value="Suez">Suez</option>
